export enum ReasonTypes {
  MOVEMENT_USED_MANY_TIMES = 'MOVEMENT_USED_MANY_TIMES',
  MOVEMENTS_IS_NOT_COMPATIBLE_CHECPOINTS = 'MOVEMENTS_IS_NOT_COMPATIBLE_CHECPOINTS',
  CHECKPOINT_USED_MANY_TIMES = 'CHECKPOINT_USED_MANY_TIMES',
}

export enum ReasonTitles {
  MOVEMENT_USED_MANY_TIMES = 'Movement used many times',
  MOVEMENTS_IS_NOT_COMPATIBLE_CHECPOINTS = 'Movement is not compatible with checkpoints',
  CHECKOPINT_USED_MANY_TIMES = 'Checkpoint used many times',
}
